// Generated by grunt: browserify-imports
(function moduleInit_yodaDashboard() {

	// require('../yoda.helpers.filters');
	// require('ace-editor-builds');
	require('angular-ui-ace');

	// Add require for other modules here
	require('../yoda.dashboard.helpers');
	require('../yoda.dashboard.components');
	require('../yoda.dashboard.docs');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./brand-switch');
	require('./component-page');
	require('./coverage-page');
	require('./modules-service');
	require('./home-page');
	require('./layout');
	require('./menu');
	var modules = ["yoda.dashboard.brandSwitch","yoda.dashboard.componentPage","yoda.dashboard.coveragePage","yoda.dashboard.modulesService","yoda.dashboard.homePage","yoda.dashboard.layout","yoda.dashboard.menu"];
	// EndRequire

	// Add your angular module dependencies here
	modules.push('ui.ace');
	modules.push('yoda.dashboard.helpers');
	modules.push('yoda.dashboard.components');
	modules.push('yoda.dashboard.docs');

	angular.module('yoda.dashboard', modules);

})();
