// Generated by grunt: browserify-imports
(function moduleInit_guiNgFormsFieldsets() {

	// Add require for other modules here
	require('angular-messages');
	require('../gui.ng.forms.components');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./input-row');
	var modules = ["gui.ng.forms.fieldsets.inputRow"];
	// EndRequire

	// Add your angular module dependencies here
	modules.push('ngMessages');
	modules.push('gui.ng.forms.components');

	angular.module('gui.ng.forms.fieldsets', modules);

})();
