// Generated by grunt: browserify-imports
(function moduleInit_guiComponents() {

	// Add require for other modules here
	// require('../../libs/grunt-icons-loader.js');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	var modules = [];
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('other.module');
	angular.module('gui.blend', modules);

})();
