// Generated by grunt: browserify-imports
(function moduleInit_appnameApp() {

	// librairies
	require('angular');
	require('angular-aria');
	require('restangular');
	require('angular-ui-router');

	// ngAnimate
	require('angular-animate');
	// angular load for dynamically loading css after getting the brand
	require('angular-load');
	require('angular-sanitize');

	require('../gui.ng.components');

	// appname modules
	require('../appname.factories');
	require('../appname.filters');
	require('./app-layout');
	require('../appname.accessibility');
	require('../appname.common');
	require('../appname.welcome');
	require('../appname.myform');
	require('../appname.preferences');
	var modules = [];

	// libs
	modules.push('restangular');
	modules.push('ngAnimate');
	modules.push('ui.router');
	modules.push('ngAria');
	modules.push('angularLoad');
	modules.push('ngSanitize');

	// common
	modules.push('gui.ng.components');

	// appname modules
	modules.push('appname.factories');
	modules.push('appname.filters');
		modules.push('appname.accessibility');
	modules.push('appname.common');
	modules.push('appname.welcome');
	modules.push('appname.myform');
		modules.push('appname.preferences');
	modules.push('appname.app.appLayout');

	// create appname app module
	angular.module('appname', modules);

	// add routes configuration
	require('./routes/app-routes');
})();
