// Generated by grunt: browserify-imports
(function moduleInit_yodadashboardHelpers() {

	// Add require for other modules here
	// require('my.module.core');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./string-helper');
	var angularModuleDependencies = ["yoda.dashboard.helpers.stringHelper"];
	// EndRequire

	// Add your angular module dependencies here
	// angularModuleDependencies.push('yoda.dashboard.helpers.stringHelper');
	angular.module('yoda.dashboard.helpers', angularModuleDependencies);

})();
