// Generated by grunt: browserify-imports
(function moduleInit_yodaDashboardComponents() {

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./cem');
	var modules = ["yoda.dashboard.docs.cem",];
	// EndRequire

	angular.module('yoda.dashboard.docs', modules);

})();
