// Generated by grunt: browserify-imports
(function moduleInit_lalaFactories() {
	'use strict';
	// Add require for other modules here
	require('./core/generic-factory.js');
	require('./reference/reference-factory.js');
	require('./restangular/base-restangular-factory.js');
	require('./kickstart/kickstart-factory.js');
	require('./brandswitch/brandswitch-factory.js');
	require('./contentmgnt/contentmgnt-factory.js');
	require('./user/user-factory.js');
	require('./demo/demo-factory.js');

	// Add your angular module dependencies here
	var modules = [];

	modules.push('appname.factories.core');
	modules.push('appname.factories.contentmgnt');
	modules.push('appname.factories.reference');
	modules.push('appname.factories.restangular');
	modules.push('appname.factories.kickstart');
	modules.push('appname.factories.brandswitch');
	modules.push('appname.factories.user');
	modules.push('appname.factories.demo');


	angular.module('appname.factories', modules);
})();
