// Generated by grunt: browserify-imports
(function moduleInit_appnamemulticomponent() {
	'use strict';

	// Add require for other modules here
	// require('../my.other.module');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./top');
	require('./side');
	require('./bottom');
	require('./center');
	require('./layout');
	var modules = [
		"appname.common.multicomponent.top",
		"appname.common.multicomponent.side",
		"appname.common.multicomponent.bottom",
		"appname.common.multicomponent.center",
		"appname.common.multicomponent.multicomponentLayout"
	];
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('my.other.module');

	angular.module('appname.common.multicomponent', modules);
})();
