// Generated by grunt: browserify-imports
(function moduleInit_appnamePreferences() {
    'use strict';

    // Add require for other modules here
    // require('../my.other.module');

    // Grunt browserify-imports require all components with an index.js here
    // StartRequire
	require('./preferences-form');
	require('./preferences-layout');
	var modules = ["appname.preferences.preferencesForm","appname.preferences.preferencesLayout"];
	// EndRequire

    // Add your angular module dependencies here
    // modules.push('my.other.module');

    angular.module('appname.preferences', modules);
})();
