// Generated by grunt: browserify-imports
(function moduleInit_appnameWelcome() {
	'use strict';

	// Add require for other modules here
	// require('../my.other.module');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./welcome-help');
	var modules = ["appname.welcome.welcomeHelp"];
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('my.other.module');

	angular.module('appname.welcome', modules);
})();
