// Generated by grunt: browserify-imports
(function moduleInit_appnameAccessibility() {
    'use strict';

    // Add require for other modules here
    // require('../my.other.module');

    // Grunt browserify-imports require all components with an index.js here
    // StartRequire
	require('./trap');
	var modules = ["appname.accessibility.trap"];
	// EndRequire

    // Add your angular module dependencies here
    // modules.push('my.other.module');

    angular.module('appname.accessibility', modules);
})();
