// Generated by grunt: browserify-imports
(function moduleInit_yodaApp() {
	// Angular

	// librairies
	// var angular = require("angular");
	var router = require('angular-ui-router');
	var ocLazyLoad = require('oclazyload');
	var ngAnimate = require('angular-animate');
	var ngAria = require('angular-aria');
	// var ngMaterial = require('angular-material');
	// var ngIcons = require('angular-material-icons');
	var catwalk = require('../yoda.catwalk');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./routes');
	var modules = [];
	// EndRequire

	// Add your angular module dependencies here
	modules.push('oc.lazyLoad');
	// modules.push('ngMaterial');
	// modules.push('ngMdIcons');
	modules.push('ui.router');
	modules.push('yoda.catwalk');
	// modules.push('yoda.catwalk.components');

	angular.module('yoda', modules);

})();
