// Generated by grunt: browserify-imports
(function moduleInit_yodaCatwalk() {

	// require('../yoda.helpers.filters');
	// require('ace-editor-builds');
	require('angular-ui-ace');

	// Add require for other modules here
	require('../yoda.catwalk.helpers');
	require('../yoda.catwalk.components');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./component-page');
	require('./coverage-page');
	require('./data');
	require('./home-page');
	require('./layout');
	require('./menu');
	var modules = ["yoda.catwalk.componentPage","yoda.catwalk.coveragePage","yoda.catwalk.data","yoda.catwalk.homePage","yoda.catwalk.layout","yoda.catwalk.menu"];
	// EndRequire

	// Add your angular module dependencies here
	modules.push('ui.ace');
	modules.push('yoda.catwalk.helpers');
	modules.push('yoda.catwalk.components');

	angular.module('yoda.catwalk', modules);

})();
