// Generated by grunt: browserify-imports
(function moduleInit_appnameaddresscomponent() {
	'use strict';

	// Add require for other modules here
	// require('../my.other.module');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./predictive-address-search');
	require('./non-standard-address/index');
	require('./layout');

	var modules = ["appname.common.predictiveAddressSearch","appname.common.nonStandardAddress",
	"appname.common.addressComponentLayout"];
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('my.other.module');

	angular.module('appname.common.addressComponent', modules);
})();
