// Generated by grunt: browserify-imports
(function moduleInit_appnameCommon() {
	'use strict';

	// Add require for other modules here
	// require('../my.other.module');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./back-button');
	require('./child');
	require('./dropdown');
	require('./footer');
	require('./header');
	require('./lower-case-onblur');
	require('./modal');
	require('./parent');
	require('./progress-bar');
	require('./tabs');
	require('./validate');
	var modules = ["appname.common.backButton","appname.common.child","appname.common.dropdown","appname.common.footer","appname.common.header","appname.common.lowerCaseOnblur","appname.common.modal","appname.common.parent","appname.common.progressBar","appname.common.tabs","appname.common.validate"];
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('my.other.module');

	angular.module('appname.common', modules);
})();
