// Generated by grunt: browserify-imports
(function moduleInit_guiNgComponents() {

	// Add require for other modules here
	// require('my.module.core');


	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./alert');
	require('./grunticon-embed');
	var modules = ["gui.ng.components.alert","gui.ng.components.grunticonEmbed"];
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('other.module');

	angular.module('gui.ng.components', modules);

})();
