// Generated by grunt: browserify-imports
(function moduleInit_guiNgForms() {

	// Add require for other modules here
	require('../gui.ng.components');
	require('../gui.ng.forms.fieldsets');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./register');
	var modules = ["gui.ng.forms.register"];
	// EndRequire

	// Add your angular module dependencies here
	modules.push('gui.ng.components');
	modules.push('gui.ng.forms.fieldsets');

	angular.module('gui.ng.forms', modules);

})();
