// Generated by grunt: browserify-imports
(function moduleInit_yodaCatwalkHelpers() {

	// Add require for other modules here
	// require('my.module.core');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./string-helper');
	var modules = ["yoda.catwalk.helpers.stringHelper"];
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('yoda.catwalk.helpers.stringHelper');

	try {
		console.log('loading module yoda.catwalk.helpers');
		angular.module('yoda.catwalk.helpers', modules);
	} catch (e) {
		console.log('yoda.catwalk.helpers is already defined.');}
	}
)();
