// Generated by grunt: browserify-imports
(function moduleInit_moduleName() {
	'use strict';

	// Add require for other modules here
	// require('../my.other.module');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	// EndRequire

	// Add your angular module dependencies here
	// modules.push('my.other.module');

	angular.module('module.name', modules);
})();
