// Generated by grunt: browserify-imports
(function moduleInit_yodaApp() {

	// librairies
	// var angular = require("angular");
	var router = require('angular-ui-router');
	var ocLazyLoad = require('oclazyload');
	var ngAnimate = require('angular-animate');
	var ngAria = require('angular-aria');
	var dashboard = require('../yoda.dashboard');

	// Grunt browserify-imports require all components with an index.js here
	// StartRequire
	require('./routes');
	var modules = [];
	// EndRequire

	modules.push('appname');

	// Add your angular module dependencies here
	modules.push('oc.lazyLoad');
	modules.push('ui.router');
	modules.push('yoda.dashboard');

	angular.module('yoda', modules);

})();
